spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Bank accounts related Pre-Production APIs "
  contactDetails:
    name: "Pavan - Developer"
    email: "Anandnand5173@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345